// Generated by scripts/build-gallery.py. Do not edit by hand.
export type Shot = { src: string; thumb: string; w: number; h: number; group: string; caption: string };

export const gallery: Record<string, Shot[]> = {
  "rfid-warehouse": [
    {
      "src": "/projects/rfid-warehouse/01.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/01.webp",
      "w": 1279,
      "h": 720,
      "group": "Web Dashboard",
      "caption": "End-to-end flow: warehouse picking, RFID gate, auto IT/IR, assembly"
    },
    {
      "src": "/projects/rfid-warehouse/02.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/02.webp",
      "w": 1902,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "Landing dashboard: live picking, gate and IT status per shift"
    },
    {
      "src": "/projects/rfid-warehouse/03.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/03.webp",
      "w": 1919,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "Main admin dashboard"
    },
    {
      "src": "/projects/rfid-warehouse/04.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/04.webp",
      "w": 1919,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "Monitoring Warehouse to Assembly process"
    },
    {
      "src": "/projects/rfid-warehouse/05.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/05.webp",
      "w": 1919,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "Kanban process with Inventory Transfer & Receipt"
    },
    {
      "src": "/projects/rfid-warehouse/06.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/06.webp",
      "w": 1916,
      "h": 942,
      "group": "Web Dashboard",
      "caption": "Kanban detail per line"
    },
    {
      "src": "/projects/rfid-warehouse/07.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/07.webp",
      "w": 1916,
      "h": 952,
      "group": "Web Dashboard",
      "caption": "Inventory Transfer (IT) documents"
    },
    {
      "src": "/projects/rfid-warehouse/08.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/08.webp",
      "w": 1914,
      "h": 949,
      "group": "Web Dashboard",
      "caption": "User activity log for traceability"
    },
    {
      "src": "/projects/rfid-warehouse/09.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/09.webp",
      "w": 868,
      "h": 931,
      "group": "Web Dashboard",
      "caption": "Printable transfer document with QR code"
    },
    {
      "src": "/projects/rfid-warehouse/10.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/10.webp",
      "w": 1903,
      "h": 1069,
      "group": "Web Dashboard",
      "caption": "Web admin login"
    },
    {
      "src": "/projects/rfid-warehouse/11.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/11.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Login by tapping the NFC employee card"
    },
    {
      "src": "/projects/rfid-warehouse/12.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/12.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Fallback login with NIK & password"
    },
    {
      "src": "/projects/rfid-warehouse/13.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/13.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Kanban list per assembly line"
    },
    {
      "src": "/projects/rfid-warehouse/14.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/14.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Scan the RFID tag on the lorry"
    },
    {
      "src": "/projects/rfid-warehouse/15.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/15.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "RFID tag detected"
    },
    {
      "src": "/projects/rfid-warehouse/16.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/16.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Item breakdown to pick"
    },
    {
      "src": "/projects/rfid-warehouse/17.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/17.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Scan rack QR to validate the location"
    },
    {
      "src": "/projects/rfid-warehouse/18.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/18.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Assembly to Delivery: operator menu"
    },
    {
      "src": "/projects/rfid-warehouse/19.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/19.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Start a delivery booking"
    },
    {
      "src": "/projects/rfid-warehouse/20.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/20.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Scan part card & packaging RFID"
    },
    {
      "src": "/projects/rfid-warehouse/21.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/21.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Booking progress per customer"
    },
    {
      "src": "/projects/rfid-warehouse/22.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/22.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Scan booking ID"
    },
    {
      "src": "/projects/rfid-warehouse/23.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/23.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Confirm the load"
    },
    {
      "src": "/projects/rfid-warehouse/24.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/24.webp",
      "w": 640,
      "h": 1280,
      "group": "Mobile App",
      "caption": "Booking saved"
    },
    {
      "src": "/projects/rfid-warehouse/25.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/25.webp",
      "w": 573,
      "h": 708,
      "group": "On the Floor",
      "caption": "Operator opens the kanban list"
    },
    {
      "src": "/projects/rfid-warehouse/26.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/26.webp",
      "w": 474,
      "h": 660,
      "group": "On the Floor",
      "caption": "Scanning the RFID tag on the lorry"
    },
    {
      "src": "/projects/rfid-warehouse/27.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/27.webp",
      "w": 585,
      "h": 905,
      "group": "On the Floor",
      "caption": "Scanning the rack QR code"
    },
    {
      "src": "/projects/rfid-warehouse/28.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/28.webp",
      "w": 582,
      "h": 824,
      "group": "On the Floor",
      "caption": "Auto-filled item, operator confirms"
    },
    {
      "src": "/projects/rfid-warehouse/29.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/29.webp",
      "w": 578,
      "h": 725,
      "group": "On the Floor",
      "caption": "Quantity fulfilled, next item"
    },
    {
      "src": "/projects/rfid-warehouse/30.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/30.webp",
      "w": 582,
      "h": 775,
      "group": "On the Floor",
      "caption": "Moving parts onto the lorry"
    },
    {
      "src": "/projects/rfid-warehouse/31.webp",
      "thumb": "/projects/rfid-warehouse/thumbs/31.webp",
      "w": 577,
      "h": 746,
      "group": "On the Floor",
      "caption": "Kanban complete, lorry ready to ship"
    }
  ],
  "inspection-room": [
    {
      "src": "/projects/inspection-room/01.webp",
      "thumb": "/projects/inspection-room/thumbs/01.webp",
      "w": 1919,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "QA dashboard with KPI cards and filters"
    },
    {
      "src": "/projects/inspection-room/02.webp",
      "thumb": "/projects/inspection-room/thumbs/02.webp",
      "w": 1915,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "Register items entering the inspection room"
    },
    {
      "src": "/projects/inspection-room/03.webp",
      "thumb": "/projects/inspection-room/thumbs/03.webp",
      "w": 1911,
      "h": 1079,
      "group": "Web Dashboard",
      "caption": "Progress list with start / complete check actions"
    },
    {
      "src": "/projects/inspection-room/04.webp",
      "thumb": "/projects/inspection-room/thumbs/04.webp",
      "w": 1916,
      "h": 1076,
      "group": "Reports",
      "caption": "Daily report per shift"
    },
    {
      "src": "/projects/inspection-room/05.webp",
      "thumb": "/projects/inspection-room/thumbs/05.webp",
      "w": 1565,
      "h": 1029,
      "group": "Reports",
      "caption": "Monthly inspection activity"
    },
    {
      "src": "/projects/inspection-room/06.webp",
      "thumb": "/projects/inspection-room/thumbs/06.webp",
      "w": 1919,
      "h": 1079,
      "group": "Reports",
      "caption": "Monthly charts per machine"
    },
    {
      "src": "/projects/inspection-room/07.webp",
      "thumb": "/projects/inspection-room/thumbs/07.webp",
      "w": 1910,
      "h": 943,
      "group": "Master Data",
      "caption": "Machine master data"
    },
    {
      "src": "/projects/inspection-room/08.webp",
      "thumb": "/projects/inspection-room/thumbs/08.webp",
      "w": 1911,
      "h": 942,
      "group": "Master Data",
      "caption": "User roles"
    },
    {
      "src": "/projects/inspection-room/09.webp",
      "thumb": "/projects/inspection-room/thumbs/09.webp",
      "w": 1908,
      "h": 931,
      "group": "Master Data",
      "caption": "Login page"
    }
  ],
  "incoming-qa": [
    {
      "src": "/projects/incoming-qa/01.webp",
      "thumb": "/projects/incoming-qa/thumbs/01.webp",
      "w": 1904,
      "h": 1079,
      "group": "Dashboard",
      "caption": "Dashboard: today's arrivals, pending checks, open problems, OK/NG per part"
    },
    {
      "src": "/projects/incoming-qa/02.webp",
      "thumb": "/projects/incoming-qa/thumbs/02.webp",
      "w": 1901,
      "h": 944,
      "group": "Arrivals",
      "caption": "Incoming goods list per supplier"
    },
    {
      "src": "/projects/incoming-qa/03.webp",
      "thumb": "/projects/incoming-qa/thumbs/03.webp",
      "w": 1907,
      "h": 938,
      "group": "Arrivals",
      "caption": "Record check result: visual / dimension, mill sheet, qty OK & NG"
    },
    {
      "src": "/projects/incoming-qa/04.webp",
      "thumb": "/projects/incoming-qa/thumbs/04.webp",
      "w": 1919,
      "h": 940,
      "group": "Problem NG",
      "caption": "Log an NG problem with supplier, part and photos"
    },
    {
      "src": "/projects/incoming-qa/05.webp",
      "thumb": "/projects/incoming-qa/thumbs/05.webp",
      "w": 1916,
      "h": 950,
      "group": "Problem NG",
      "caption": "Problem detail"
    },
    {
      "src": "/projects/incoming-qa/06.webp",
      "thumb": "/projects/incoming-qa/thumbs/06.webp",
      "w": 1917,
      "h": 949,
      "group": "Problem NG",
      "caption": "Corrective analysis; closed problems are locked"
    },
    {
      "src": "/projects/incoming-qa/07.webp",
      "thumb": "/projects/incoming-qa/thumbs/07.webp",
      "w": 1897,
      "h": 934,
      "group": "Login",
      "caption": "Login page"
    }
  ],
  "calibration": [
    {
      "src": "/projects/calibration/01.webp",
      "thumb": "/projects/calibration/thumbs/01.webp",
      "w": 1919,
      "h": 1079,
      "group": "Dashboard",
      "caption": "Main dashboard: KPIs, plan vs actual, priority list"
    },
    {
      "src": "/projects/calibration/02.webp",
      "thumb": "/projects/calibration/thumbs/02.webp",
      "w": 1919,
      "h": 1079,
      "group": "Dashboard",
      "caption": "Automatic due-date notifications"
    },
    {
      "src": "/projects/calibration/03.webp",
      "thumb": "/projects/calibration/thumbs/03.webp",
      "w": 1919,
      "h": 1079,
      "group": "Internal Calibration",
      "caption": "Internal calibration list"
    },
    {
      "src": "/projects/calibration/04.webp",
      "thumb": "/projects/calibration/thumbs/04.webp",
      "w": 1919,
      "h": 1073,
      "group": "Internal Calibration",
      "caption": "Create a schedule"
    },
    {
      "src": "/projects/calibration/05.webp",
      "thumb": "/projects/calibration/thumbs/05.webp",
      "w": 1916,
      "h": 1075,
      "group": "Internal Calibration",
      "caption": "Pick an instrument to input"
    },
    {
      "src": "/projects/calibration/06.webp",
      "thumb": "/projects/calibration/thumbs/06.webp",
      "w": 1919,
      "h": 1079,
      "group": "Internal Calibration",
      "caption": "Input calibration results"
    },
    {
      "src": "/projects/calibration/07.webp",
      "thumb": "/projects/calibration/thumbs/07.webp",
      "w": 1919,
      "h": 1079,
      "group": "Internal Calibration",
      "caption": "Submit for review"
    },
    {
      "src": "/projects/calibration/08.webp",
      "thumb": "/projects/calibration/thumbs/08.webp",
      "w": 1911,
      "h": 943,
      "group": "Internal Calibration",
      "caption": "Supervisor approval"
    },
    {
      "src": "/projects/calibration/09.webp",
      "thumb": "/projects/calibration/thumbs/09.webp",
      "w": 1919,
      "h": 1079,
      "group": "External Calibration",
      "caption": "External calibration list"
    },
    {
      "src": "/projects/calibration/10.webp",
      "thumb": "/projects/calibration/thumbs/10.webp",
      "w": 1919,
      "h": 1079,
      "group": "External Calibration",
      "caption": "Create an external schedule"
    },
    {
      "src": "/projects/calibration/11.webp",
      "thumb": "/projects/calibration/thumbs/11.webp",
      "w": 1919,
      "h": 1079,
      "group": "External Calibration",
      "caption": "Open the process page"
    },
    {
      "src": "/projects/calibration/12.webp",
      "thumb": "/projects/calibration/thumbs/12.webp",
      "w": 1919,
      "h": 1079,
      "group": "External Calibration",
      "caption": "10-step process: PP, PO, shipping, certificate"
    },
    {
      "src": "/projects/calibration/13.webp",
      "thumb": "/projects/calibration/thumbs/13.webp",
      "w": 1907,
      "h": 951,
      "group": "External Calibration",
      "caption": "Approval once all steps are done"
    },
    {
      "src": "/projects/calibration/14.webp",
      "thumb": "/projects/calibration/thumbs/14.webp",
      "w": 1919,
      "h": 1079,
      "group": "External Calibration",
      "caption": "Completed and locked for audit trail"
    },
    {
      "src": "/projects/calibration/15.webp",
      "thumb": "/projects/calibration/thumbs/15.webp",
      "w": 1919,
      "h": 1079,
      "group": "Reports",
      "caption": "Instrument master report"
    },
    {
      "src": "/projects/calibration/16.webp",
      "thumb": "/projects/calibration/thumbs/16.webp",
      "w": 1919,
      "h": 1079,
      "group": "Reports",
      "caption": "Due date & overdue report"
    },
    {
      "src": "/projects/calibration/17.webp",
      "thumb": "/projects/calibration/thumbs/17.webp",
      "w": 1919,
      "h": 1079,
      "group": "Reports",
      "caption": "Plan vs actual achievement"
    },
    {
      "src": "/projects/calibration/18.webp",
      "thumb": "/projects/calibration/thumbs/18.webp",
      "w": 1919,
      "h": 1079,
      "group": "Reports",
      "caption": "Supplier performance"
    },
    {
      "src": "/projects/calibration/19.webp",
      "thumb": "/projects/calibration/thumbs/19.webp",
      "w": 1919,
      "h": 1079,
      "group": "Master Data",
      "caption": "Master data overview"
    },
    {
      "src": "/projects/calibration/20.webp",
      "thumb": "/projects/calibration/thumbs/20.webp",
      "w": 1919,
      "h": 1079,
      "group": "Master Data",
      "caption": "Measuring instruments"
    },
    {
      "src": "/projects/calibration/21.webp",
      "thumb": "/projects/calibration/thumbs/21.webp",
      "w": 1919,
      "h": 1079,
      "group": "Master Data",
      "caption": "Instrument categories & intervals"
    },
    {
      "src": "/projects/calibration/22.webp",
      "thumb": "/projects/calibration/thumbs/22.webp",
      "w": 1919,
      "h": 1079,
      "group": "Master Data",
      "caption": "Calibration suppliers"
    }
  ],
  "skill-matrix": [
    {
      "src": "/projects/skill-matrix/01.webp",
      "thumb": "/projects/skill-matrix/thumbs/01.webp",
      "w": 1794,
      "h": 1526,
      "group": "Web Dashboard",
      "caption": "Web display after an NFC scan"
    },
    {
      "src": "/projects/skill-matrix/02.webp",
      "thumb": "/projects/skill-matrix/thumbs/02.webp",
      "w": 1919,
      "h": 945,
      "group": "Web Dashboard",
      "caption": "Web NFC scan display"
    },
    {
      "src": "/projects/skill-matrix/03.webp",
      "thumb": "/projects/skill-matrix/thumbs/03.webp",
      "w": 1912,
      "h": 944,
      "group": "Web Dashboard",
      "caption": "Admin dashboard"
    },
    {
      "src": "/projects/skill-matrix/04.webp",
      "thumb": "/projects/skill-matrix/thumbs/04.webp",
      "w": 1914,
      "h": 944,
      "group": "Web Dashboard",
      "caption": "Employee skill list"
    },
    {
      "src": "/projects/skill-matrix/05.webp",
      "thumb": "/projects/skill-matrix/thumbs/05.webp",
      "w": 1919,
      "h": 1078,
      "group": "Web Dashboard",
      "caption": "Skill score input"
    },
    {
      "src": "/projects/skill-matrix/06.webp",
      "thumb": "/projects/skill-matrix/thumbs/06.webp",
      "w": 1919,
      "h": 942,
      "group": "Web Dashboard",
      "caption": "Employee knowledge"
    },
    {
      "src": "/projects/skill-matrix/07.webp",
      "thumb": "/projects/skill-matrix/thumbs/07.webp",
      "w": 1915,
      "h": 943,
      "group": "Web Dashboard",
      "caption": "Employee training"
    },
    {
      "src": "/projects/skill-matrix/08.webp",
      "thumb": "/projects/skill-matrix/thumbs/08.webp",
      "w": 1919,
      "h": 939,
      "group": "Web Dashboard",
      "caption": "Training score input"
    },
    {
      "src": "/projects/skill-matrix/09.webp",
      "thumb": "/projects/skill-matrix/thumbs/09.webp",
      "w": 1919,
      "h": 934,
      "group": "Web Dashboard",
      "caption": "Skill scores"
    },
    {
      "src": "/projects/skill-matrix/10.webp",
      "thumb": "/projects/skill-matrix/thumbs/10.webp",
      "w": 1919,
      "h": 782,
      "group": "Web Dashboard",
      "caption": "Knowledge scores"
    },
    {
      "src": "/projects/skill-matrix/11.webp",
      "thumb": "/projects/skill-matrix/thumbs/11.webp",
      "w": 1869,
      "h": 935,
      "group": "Web Dashboard",
      "caption": "Login"
    },
    {
      "src": "/projects/skill-matrix/12.webp",
      "thumb": "/projects/skill-matrix/thumbs/12.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Waiting for an NFC employee card"
    },
    {
      "src": "/projects/skill-matrix/13.webp",
      "thumb": "/projects/skill-matrix/thumbs/13.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Employee profile and skill map after scan"
    },
    {
      "src": "/projects/skill-matrix/14.webp",
      "thumb": "/projects/skill-matrix/thumbs/14.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Inspector requirements"
    },
    {
      "src": "/projects/skill-matrix/15.webp",
      "thumb": "/projects/skill-matrix/thumbs/15.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Basic training quality scores"
    },
    {
      "src": "/projects/skill-matrix/16.webp",
      "thumb": "/projects/skill-matrix/thumbs/16.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Skill quality detail"
    },
    {
      "src": "/projects/skill-matrix/17.webp",
      "thumb": "/projects/skill-matrix/thumbs/17.webp",
      "w": 720,
      "h": 1440,
      "group": "Mobile App",
      "caption": "Evaluation result and skill level"
    }
  ],
  "robot-problem": [
    {
      "src": "/projects/robot-problem/01.webp",
      "thumb": "/projects/robot-problem/thumbs/01.webp",
      "w": 1918,
      "h": 943,
      "group": "Admin Dashboard",
      "caption": "Admin dashboard: lines, production and problems today"
    },
    {
      "src": "/projects/robot-problem/02.webp",
      "thumb": "/projects/robot-problem/thumbs/02.webp",
      "w": 1919,
      "h": 941,
      "group": "Admin Dashboard",
      "caption": "Production chart: summary vs target"
    },
    {
      "src": "/projects/robot-problem/03.webp",
      "thumb": "/projects/robot-problem/thumbs/03.webp",
      "w": 1916,
      "h": 942,
      "group": "Admin Dashboard",
      "caption": "Daily production pivot per line"
    },
    {
      "src": "/projects/robot-problem/04.webp",
      "thumb": "/projects/robot-problem/thumbs/04.webp",
      "w": 1918,
      "h": 935,
      "group": "Admin Dashboard",
      "caption": "Problem summary and lost time"
    },
    {
      "src": "/projects/robot-problem/05.webp",
      "thumb": "/projects/robot-problem/thumbs/05.webp",
      "w": 1919,
      "h": 932,
      "group": "Admin Dashboard",
      "caption": "Production records"
    },
    {
      "src": "/projects/robot-problem/06.webp",
      "thumb": "/projects/robot-problem/thumbs/06.webp",
      "w": 1919,
      "h": 942,
      "group": "Admin Dashboard",
      "caption": "Problem records"
    },
    {
      "src": "/projects/robot-problem/07.webp",
      "thumb": "/projects/robot-problem/thumbs/07.webp",
      "w": 1919,
      "h": 945,
      "group": "Admin Dashboard",
      "caption": "Line master with daily target"
    },
    {
      "src": "/projects/robot-problem/08.webp",
      "thumb": "/projects/robot-problem/thumbs/08.webp",
      "w": 1919,
      "h": 944,
      "group": "Admin Dashboard",
      "caption": "Machine master"
    },
    {
      "src": "/projects/robot-problem/09.webp",
      "thumb": "/projects/robot-problem/thumbs/09.webp",
      "w": 723,
      "h": 909,
      "group": "Mobile App",
      "caption": "Login with employee NIK"
    },
    {
      "src": "/projects/robot-problem/10.webp",
      "thumb": "/projects/robot-problem/thumbs/10.webp",
      "w": 695,
      "h": 913,
      "group": "Mobile App",
      "caption": "Home: shift info and main menu"
    },
    {
      "src": "/projects/robot-problem/11.webp",
      "thumb": "/projects/robot-problem/thumbs/11.webp",
      "w": 702,
      "h": 904,
      "group": "Mobile App",
      "caption": "Production per robot line"
    },
    {
      "src": "/projects/robot-problem/12.webp",
      "thumb": "/projects/robot-problem/thumbs/12.webp",
      "w": 766,
      "h": 904,
      "group": "Mobile App",
      "caption": "Input a robot problem; lost time auto-calculated"
    },
    {
      "src": "/projects/robot-problem/13.webp",
      "thumb": "/projects/robot-problem/thumbs/13.webp",
      "w": 785,
      "h": 911,
      "group": "Mobile App",
      "caption": "Problem detail and corrective action"
    },
    {
      "src": "/projects/robot-problem/14.webp",
      "thumb": "/projects/robot-problem/thumbs/14.webp",
      "w": 722,
      "h": 904,
      "group": "Mobile App",
      "caption": "Problem history"
    },
    {
      "src": "/projects/robot-problem/15.webp",
      "thumb": "/projects/robot-problem/thumbs/15.webp",
      "w": 820,
      "h": 914,
      "group": "Mobile App",
      "caption": "Input production"
    },
    {
      "src": "/projects/robot-problem/16.webp",
      "thumb": "/projects/robot-problem/thumbs/16.webp",
      "w": 648,
      "h": 912,
      "group": "Mobile App",
      "caption": "Production history"
    },
    {
      "src": "/projects/robot-problem/17.webp",
      "thumb": "/projects/robot-problem/thumbs/17.webp",
      "w": 802,
      "h": 898,
      "group": "Mobile App",
      "caption": "Edit production record"
    }
  ],
  "control-room": [
    {
      "src": "/projects/control-room/01.webp",
      "thumb": "/projects/control-room/thumbs/01.webp",
      "w": 1919,
      "h": 1075,
      "group": "Dashboard",
      "caption": "Plant performance overview with CCTV AI events and live alerts"
    }
  ]
};
